---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: proctor-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: proctorprod.azurecr.io/userservice:$tag
          imagePullPolicy: Always
          env:
            - name: DATA_SERVICE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: proctor-prod-env
                  key: DATA_SERVICE_ENDPOINT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: proctor-prod-env
                  key: MONGO_URI
      imagePullSecrets:
        - name: mysecret
