---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: proctorprod.azurecr.io/userservice:$tag
          imagePullPolicy: Always
          env:
            - name: DATA_SERVICE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: proctor-prod-env
                  key: DATA_SERVICE_ENDPOINT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: proctor-prod-env
                  key: MONGO_URI
            - name: Endpoint
              valueFrom:
                secretKeyRef:
                  name: proctor-prod-env
                  key: Endpoint
            - name: AZURE_SERVICE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: proctor-prod-env
                  key: AZURE_SERVICE_ENDPOINT
            - name: LOCATION
              valueFrom:
                secretKeyRef:
                  name: proctor-prod-env
                  key: LOCATION
            - name: ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: proctor-prod-env
                  key: ACCOUNT_ID
            - name: CACHE_CONTROL
              valueFrom:
                secretKeyRef:
                  name: proctor-prod-env
                  key: CACHE_CONTROL
            
          ports:
          - containerPort: 3005
      imagePullSecrets:
        - name: mysecret
