apiVersion: v1
kind: Service
metadata:
  name: userservice
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: userservice
  ports:
    - port: 3005
      targetPort: 3005
  type: LoadBalancer